### ISSUE TITLE
KeyError: 'img_path'

### ISSUE THREAD

**Issue by XiaobinWu1998** [zhangzjn/ADer#26]
It seems that after updating the version, this problem has arisen

CUDA_VISIBLE_DEVICES=0 python3 run.py -c configs/benchmark/destseg/destseg_256_300e.py -m train

Traceback (most recent call last):
  File "run.py", line 31, in <module>
    main()
  File "run.py", line 27, in main
    trainer.run()
  File "/workspace/mycode/ADer-main/trainer/_base_trainer.py", line 252, in run
    self.train()
  File "/workspace/mycode/ADer-main/trainer/_base_trainer.py", line 178, in train
    self.set_input(train_data)
  File "/workspace/mycode/ADer-main/trainer/destseg_trainer.py", line 64, in set_input
    self.img_path = inputs['img_path']
KeyError: 'img_path'

**Comment by ctj1007** [comment]
How was it resolved？

**Comment by wu33learn** [comment]
> 它是如何解决的？

trainer文件里（simplenet为例）把预测时的输入修改一下，  修改前self.scores, self.preds = self.net.net_simplenet.predict(**_self.imgs)_**，修改后self.scores, self.preds = self.net.net_simplenet.predict(**_test_data_**)

**Comment by SwaggyPinqi12** [comment]
> How was it resolved？  它是如何解决的？

In DestSeg method you can refer[https://github.com/zhangzjn/ADer/issues/42](url)
