### ISSUE TITLE
(PatchCore test error) AttributeError: 'NoneType' object has no attribute 'search'

### ISSUE THREAD

**Issue by ValoraY** [zhangzjn/ADer#29]
when I run `CUDA_VISIBLE_DIVICES=0 python run.py -c configs/benchmark/patchcore/patchcore_256_100e.py -m test`,  I got message like this:

Traceback (most recent call last):
  File "/data/xxx/PROJECTS/ADer/run.py", line 31, in <module>
    main()
  File "/data/xxx/PROJECTS/ADer/run.py", line 27, in main
    trainer.run()
  File "/data/xxx/PROJECTS/ADer/trainer/patchcore_trainer.py", line 346, in run
    self.test()
  File "/home/xxx/anaconda3/envs/ader/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/xxx/PROJECTS/ADer/trainer/patchcore_trainer.py", line 233, in test
    self.scores, self.preds = self.net.net_patchcore.predict(self.imgs)
  File "/data/xxx/PROJECTS/ADer/model/patchcore.py", line 747, in predict
    patch_scores = image_scores = self.anomaly_scorer.predict([features])[0]
  File "/data/xxx/PROJECTS/ADer/model/patchcore.py", line 542, in predict
    query_distances, query_nns = self.imagelevel_nn(query_features)
  File "/data/xxx/PROJECTS/ADer/model/patchcore.py", line 505, in <lambda>
    self.imagelevel_nn = lambda query: self.nn_method.run(
  File "/data/xxx/PROJECTS/ADer/model/patchcore.py", line 275, in run
    return self.search_index.search(query_features, n_nearest_neighbours)
AttributeError: 'NoneType' object has no attribute 'search'

**Comment by fozeke** [comment]
same question

**Comment by zhangzjn** [comment]
The following command can be used:
`CUDA_VISIBLE_DEVICES=0 python run.py -c configs/benchmark/patchcore_256_100e.py -m train trainer.checkpoint=runs/benchmark/patchcore_256_100e/mvtec data.root=data/mvtec`. 
Currently, the PatchCore only supports 'train' mode. Since this method lacks a training process, it is equivalent to the test process.

**Comment by Vzoooong** [comment]
same question +1

**Comment by dankling** [comment]
请问一下 用patchcore 可视化 怎么操作呢
